### ISSUE TITLE
Data management section for the nf-core documentation.

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/awsmegatests#10]
Some like the idea of having a data management section in the docs. The aim is to discuss what should be in there and who can provide that, and what other support might be needed. 

One suggestion so far is to have:
- Data planning:
    - File types: provided by workflow authors.
    - File sizes: Range provided with data from #aws-megatests
- Long term storage:
    - Link to NBIS data management pages for relevant workflows?
    - What about more specialized workflows?
    - Is there a suitable general link?
- What else?

**Comment by mahesh-panchal** [comment]
Related: https://github.com/nf-core/rnaseq/issues/400

**Comment by drpatelh** [comment]
I wonder if we can run `du -h` or similar on the `results/` and `work/` directory after the pipeline has completed? I think this would be amazing to add directly to NF because you would get storage reporting directly from NF along with all the other cool metrics. Given that it is not really going to be that informative getting these metrics from a single dataset (as we would with the AWS automated tests; although I still think it would be informative to report anyway) having this data across a multitude of input datasets, genomes etc will hopefully give us a better idea as to how much storage each NF pipeline is using. This could also possibly be integrated with NF tower to record this information across historic runs and could be used to train the predictive models that @evanfloden @pditommaso plan to use within NF tower? You can imagine it as a benchmarking for storage as an addition to the similar plans you have for compute resources. Maybe I'm getting a bit too ahead of myself but it was just a thought 😅 

Submitting data to a public repository is a bit of a tricky one. I tend to use GEO because it's not that painful compared to other databases (haven't checked recently to be honest). However, we tend to do this just before publication because its very difficult to tell whether any given dataset is going to make it through to publication. Also, there is a manual element involved in filling in a data metasheet which makes more sense to do when scientists know the content of the publication and what data to include. However, I have thought about automating certain aspects of this:
https://github.com/nf-core/atacseq/issues/32

Im not sure if thats what you meant @YvonneKallberg?

**Comment by mahesh-panchal** [comment]
Personally I think the results of `du -sh` are fine in the report, but there needs to be a more general data range given some input range to allow PI's to plan experiments. The numbers are often needed long before an experiment is run. 

Can nf-tower assist with this as well?

**Comment by pditommaso** [comment]
Tower already reports the total disk writes, check the * Aggregate stats* box on the right. However, it should be said *IO* metrics are a bit of grey area in Linux, therefore I'm 100% sure how that numbers are accurate. If you could compare with your observations it would be very valuable. After that, we can see how to improve it.

**Comment by ewels** [comment]
Also, IO metrics can be very different to the final storage space required to keep the results from `publishDir`, especially if there are large intermediate files. `du -sh` of the output directory may be more informative, even if it is a little hacky.

**Comment by mahesh-panchal** [comment]
Is it worth then having a section in a workflow report (i.e. from MultiQC) that has the output folder structure, and a rounded data size on the folder leaf.
e.g.
```
/results (5GB)
 | - 01_Fastqc (100MB)
 | - 02_Fastp (500MB)
 ...
 \- XX_MultiQC (5MB)
```

Perhaps also have as part of the repository an example output folder, which has the final reports generated from select awsmegatests. 

The workflow documentation could then also have a data planning section with the rough estimates of total output given a certain input size (based off the selected megatests). 

The estimated storage requirements though would need to record both the size of the results directory and the work directory ( not using `process.scratch` ) too.

**Comment by ewels** [comment]
> Perhaps also have as part of the repository an example output folder, which has the final reports generated from select awsmegatests.

The intention is to keep the results from the aws tests hosted in an s3 bucket. We will then make these files available through the nf-core website (either as an `<iframe>` or preferably using some javascript library for nicer integration). We can of course also try to pick out specific files to make them easier to browse - specifically MultiQC reports and pipeline reports.

I don't think that the size of the work directory is so important to have in the MultiQC report (I generally try to assume that this is for the "end user" that didn't necessarily run the pipeline). Though we could add a pipeline / MultiQC config option to turn this on and off I guess.

**Comment by mahesh-panchal** [comment]
> The intention is to keep the results from the aws tests hosted in an s3 bucket. We will then make these files available through the nf-core website (either as an `<iframe>` or preferably using some javascript library for nicer integration). We can of course also try to pick out specific files to make them easier to browse - specifically MultiQC reports and pipeline reports.

That's a better solution. When are the megatests intended to be run? Each merge to master, or release?
 
> I don't think that the size of the work directory is so important to have in the MultiQC report (I generally try to assume that this is for the "end user" that didn't necessarily run the pipeline). Though we could add a pipeline / MultiQC config option to turn this on and off I guess.

No, I don't think the work directory size should be in the Multiqc report, but in the User docs. That's where I'm suggesting a data planning section be, not in the multiqc report. To be honest, I don't think much needs to be done to the MultiQC report. It would be helpful to have a section in the MultiQC report linking back to the User docs telling them what they can do with their data (this is where I'm hoping the data management experts will chime in with what would be useful there). A folder structure description would also be useful, but again this could be better put in the User docs. I think the User docs need at least two parts to the data management section. One on planning ( estimated compute resources ), and one on data something - submission ? (What to do with data after the analysis is complete).

**Comment by pditommaso** [comment]
Keeping separate compute scratch from output files storage requirements is a good point. From NF side it should be relatively easy to compute aggregate files size that are processed by a `publishDir` directive. It wouldn't either require a `du` (which is good because it could not be possible to use it on remote storage e.g. S3).

**Comment by elinkronander** [comment]
Are you aiming for general guidelines that can apply to all pipelines, for example some points to consider when choosing resources for sharing data and then linking to a list of deposition databases and standards like https://fairsharing.org/, or would you like to identify resources to recommend for each pipeline?

**Comment by mahesh-panchal** [comment]
Ideally, resources to recommend for each pipeline, but if not, then something general. At the very least, something general could be added to the pipeline templates, and then it's down to the workflow authors and experts to suggest workflow specific resources.

**Comment by elinkronander** [comment]
I extended your original outline a bit @mahesh-panchal. We could start with some general guidelines based on this outline that could later be customized for each pipeline. Would this be too bulky for the user docs, something missing or unnecessary? 

**Data planning:**
- advise to make a DMP (recommend DSW, SLL-DSW for SLL users)
- storage/compute, see output data generated for filetypes and sizes, folder structure 
>output folder structure, and a rounded data size on the folder leaf.

> Keeping separate compute scratch from output files storage requirements is a good point. From NF side it should be relatively easy to compute aggregate files size that are processed by a publishDir directive.

- Consider to deposit data early on under embargo
- Use metadata standards from the beginning

**Sharing:**
Choosing repository, key points to consider:
- domain and data type specific, link to SLL data guidelines 
- sustainability of the repository, link to ELIXIR Core Data resources

Preparing for submission:
- choosing a license
- describing your data (metadata standards/ontologies/experimental design)
- data integrity, dm5 checksums generated by pipeline as mentioned by @drpatelh 
> However, I have thought about automating certain aspects of this:
nf-core/atacseq#32

**Comment by mahesh-panchal** [comment]
> I extended your original outline a bit @mahesh-panchal. We could start with some general guidelines based on this outline that could later be customized for each pipeline. Would this be too bulky for the user docs, something missing or unnecessary?
> 

This looks like a good size so far to me, but it's down to the core team in the end what's too much, not appropriate. 

> **Data planning:**
> 
>     * advise to make a DMP (recommend DSW, SLL-DSW for SLL users)

Could you explain what these acronyms are please?

>     * storage/compute, see output data generated for filetypes and sizes, folder structure 
>     * Consider to deposit data early on under embargo

I guess this is down to the workflow/topic experts to provide information on domain specific repositories to consider, but at the very least here we should perhaps provide a link to the  https://fairsharing.org/ databases page for a catch all situtation. 

>     * Use metadata standards from the beginning

Could you explain more what this means? Perhaps use one of the workflows to provide a more concrete example.

> 
> **Sharing:**
> Choosing repository, key points to consider:
> 
>     * domain and data type specific, link to SLL data guidelines

Do you have a link to the guidelines? 
 
>     * sustainability of the repository, link to ELIXIR Core Data resources
> 
> Preparing for submission:
> 
>     * choosing a license
>     * describing your data (metadata standards/ontologies/experimental design)
>     * data integrity, dm5 checksums generated by pipeline as mentioned by @drpatelh

**Comment by ewels** [comment]
I think a lot of this can be generalised and kept as a documentation page on the website.. 👍

**Comment by elinkronander** [comment]
Ok, we'll draft a generalized page based on the outline above where all the acronyms are explained and with functional links.

**Comment by ewels** [comment]
If you fancy it, you can make this into a PR right away for the website and we can review the text there. Just make a new markdown file in the [`markdown/usage` folder in the website repository](https://github.com/nf-core/nf-co.re/tree/master/markdown/usage). Once merged that will automatically create a new webpage + link.

Phil

**Comment by elinkronander** [comment]
I made a PR for reviewing the guidelines. 
https://github.com/nf-core/nf-co.re/pull/349

**Comment by ggabernet** [comment]
As it is already added to the website I will close this issue, it looks great there and I look forward to the talk!
